snipts/urls.py
from django.conf.urls import url
from snipts import views


urlpatterns = [
    url(
        r"^s/(?P<snipt_key>[^/]+)/(?P<lexer>[^\?]+)?$",
        views.redirect_snipt,
        name="redirect-snipt",
    ),
    url(r"^(?P<username>[^/]+)/feed/$", views.redirect_user_feed, name="redirect-feed"),
    url(
        r"^public/tag/(?P<tag_slug>[^/]+)/feed/$",
        views.redirect_public_tag_feed,
        name="redirect-public-tag-feed",
    ),
    url(
        r"^(?P<username>[^/]+)/tag/(?P<tag_slug>[^/]+)/feed/$",
        views.redirect_user_tag_feed,
        name="redirect-user-tag-feed",
    ),
    url(r"^public/$", views.list_public, name="list-public"),
    url(
        r"^public/tag/(?P<tag_slug>[^/]+)/$", views.list_public, name="list-public-tag"
    ),
    url(r'^report-spam/(?P<snipt_id>[^/]+)/$', views.report_spam, name='report-spam'),
    url(r"^download/(?P<snipt_key>[^/]+).*$", views.download, name="download"),
    url(r"^embed/(?P<snipt_key>[^/]+)/$", views.embed, name="embed"),
    url(r"^raw/(?P<snipt_key>[^/]+)/(?P<lexer>[^\?]+)?$", views.raw, name="raw"),
    url(r"^(?P<username_or_custom_slug>[^/]+)/$", views.list_user, name="list-user"),
    url(
        r"^(?P<username_or_custom_slug>[^/]+)/tag/(?P<tag_slug>[^/]+)/$",
        views.list_user,
        name="list-user-tag",
    ),
    url(r"^(?P<username>[^/]+)/favorites/$", views.favorites, name="favorites"),
    url(r"^(?P<username>[^/]+)/blog-posts/$", views.blog_posts, name="blog-posts"),
    url(r"^(?P<username>[^/]+)/(?P<snipt_slug>[^/]+)/$", views.detail, name="detail"),
]

urls.py
import os

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.views.static import serve
from snipts.api import (
    PublicSniptResource,
    PublicUserResource,
    PrivateSniptResource,
    PrivateFavoriteResource,
    PrivateUserProfileResource,
    PrivateUserResource,
    PublicTagResource,
)
# from snipts.views import search
from tastypie.api import Api
from views import homepage, lexers, login_redirect, tags, user_api_key

public_api = Api(api_name="public")
public_api.register(PublicSniptResource())
public_api.register(PublicTagResource())
public_api.register(PublicUserResource())

private_api = Api(api_name="private")
private_api.register(PrivateSniptResource())
private_api.register(PrivateUserResource())
private_api.register(PrivateFavoriteResource())
private_api.register(PrivateUserProfileResource())

urlpatterns = []

if os.environ.get("DISABLE_SIGNUP") == "true":
    urlpatterns += [
        url(r"^register/?$", lambda x: HttpResponseRedirect("/404/")),
        url(r"^signup/?$", lambda x: HttpResponseRedirect("/404/")),
    ]
else:
    urlpatterns += [url(r"^signup/?$", lambda x: HttpResponseRedirect("/register/"))]


urlpatterns += [
    url(r"^$", homepage),
    url(r"", include("registration.backends.simple.urls")),
    url(r"^login/?$", login, name="login"),
    url(r"^login-redirect/$", login_redirect),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^404/$", TemplateView.as_view(template_name="404.html")),
    url(r"^500/$", TemplateView.as_view(template_name="500.html")),
    url(r"^robots.txt$", TemplateView.as_view(template_name="robots.txt")),
    url(r"^tags/$", tags),
    url(r"^account/", include("accounts.urls")),
    url(r"^api/public/lexer/$", lexers),
    url(r"^api/private/key/$", user_api_key),
    url(r"^api/", include(public_api.urls)),
    url(r"^api/", include(private_api.urls)),
    # url(r"^search/$", search),
    url(r"^", include("teams.urls")),
    url(r"^", include("snipts.urls")),
    url(
        r"^(?P<path>favicon\.ico)$",
        serve,
        {"document_root": os.path.join(os.path.dirname(__file__), "static/img")},
    ),
    url(
        r"^static/(?P<path>.*)$",
        serve,
        {"document_root": os.path.join(os.path.dirname(__file__), "media")},
    ),
]

snipts/models.py
import datetime
import difflib
import hashlib
import random
import re

from annoying.functions import get_object_or_None
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from markdown_deux import markdown
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import get_lexer_by_name
from pygments.util import ClassNotFound
from snipts.utils import slugify_uniquely
from taggit.managers import TaggableManager
from taggit.utils import edit_string_for_tags
from teams.models import Team


class Snipt(models.Model):
    """An individual Snipt."""

    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    last_user_saved = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name="last_user_saved",
        on_delete=models.CASCADE,
    )

    title = models.CharField(max_length=255, blank=True, null=True, default="Untitled")
    slug = models.SlugField(max_length=255, blank=True)
    custom_slug = models.SlugField(max_length=255, blank=True)
    tags = TaggableManager()

    lexer = models.CharField(max_length=50)
    code = models.TextField()
    meta = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    stylized = models.TextField(blank=True, null=True)
    stylized_min = models.TextField(blank=True, null=True)
    embedded = models.TextField(blank=True, null=True)
    line_count = models.IntegerField(blank=True, null=True, default=None)

    key = models.CharField(max_length=100, blank=True, null=True)
    public = models.BooleanField(default=False)
    secure = models.BooleanField(default=False)
    blog_post = models.BooleanField(default=False)

    views = models.IntegerField(default=0)

    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)
    publish_date = models.DateTimeField(blank=True, null=True)

    def _unidiff_output(self, expected, actual):
        expected = expected.splitlines(1)
        actual = actual.splitlines(1)

        diff = difflib.unified_diff(expected, actual)

        return "".join(diff)

    def __init__(self, *args, **kwargs):
        super(Snipt, self).__init__(*args, **kwargs)
        self.original_code = self.code

    def save(self, *args, **kwargs):

        if not self.slug:
            self.slug = slugify_uniquely(self.title, Snipt)

        if not self.key:
            self.key = hashlib.md5(
                (
                    self.slug + str(datetime.datetime.now()) + str(random.random())
                ).encode("utf-8")
            ).hexdigest()

        if self.lexer == "markdown":
            self.stylized = markdown(self.code, "default")

            # Snipt embeds
            for match in re.findall('\[\[(\w{32})\]\]', self.stylized):
                self.stylized = self.stylized.replace('[[' + str(match) + ']]',
                                                      """
                        <script type="text/javascript"
                                   src="https://snipt.net/embed/{}/?snipt">
                           </script>
                       <div id="snipt-embed-{}"></div>""".format(
                        match, match
                    ),
                )

            # YouTube embeds
            for match in re.findall(
                "\[\[youtube-(\w{11})\-(\d+)x(\d+)\]\]", self.stylized
            ):
                self.stylized = self.stylized.replace(
                    "[[youtube-{}-{}x{}]]".format(
                        str(match[0]), str(match[1]), str(match[2])
                    ),
                    """<iframe width="{}" height="{}"
                           src="https://www.youtube.com/embed/{}"
                           frameborder="0" allowfullscreen></iframe>""".format(
                        match[1], match[2], match[0]
                    ),
                )

            # Vimeo embeds
            for match in re.findall("\[\[vimeo-(\d+)\-(\d+)x(\d+)\]\]", self.stylized):
                self.stylized = self.stylized.replace(
                    "[[vimeo-{}-{}x{}]]".format(
                        str(match[0]), str(match[1]), str(match[2])
                    ),
                    """<iframe src="https://player.vimeo.com/video/{}"
                           width="{}" height="{}" frameborder="0"
                           webkitAllowFullScreen mozallowfullscreen
                           allowFullScreen></iframe>""".format(
                        match[0], match[1], match[2]
                    ),
                )

            # Tweet embeds
            for match in re.findall("\[\[tweet-(\d+)\]\]", self.stylized):
                self.stylized = self.stylized.replace(
                    "[[tweet-{}]]".format(str(match)),
                    '<div class="embedded-tweet" data-tweet-id="{}"></div>'.format(
                        str(match)
                    ),
                )

            # Parse Snipt usernames
            for match in re.findall('@(\w+) ', self.stylized):

                # Try and get the Snipt user by username.
                user = get_object_or_None(User, username=match)

                if user:
                    url = user.profile.get_user_profile_url()
                    self.stylized = self.stylized.replace(
                        "@{} ".format(str(match)),
                        '<a href="{}">@{}</a> '.format(url, match),
                    )

        else:
            self.stylized = highlight(
                self.code,
                get_lexer_by_name(self.lexer, encoding="UTF-8"),
                HtmlFormatter(
                    linenos="table", anchorlinenos=True, lineanchors="L", linespans="L"
                ),
            )
        self.line_count = len(self.code.split("\n"))

        if self.lexer == "markdown":
            lexer_for_embedded = "text"
        else:
            lexer_for_embedded = self.lexer

        embedded = highlight(
            self.code,
            get_lexer_by_name(lexer_for_embedded, encoding="UTF-8"),
            HtmlFormatter(
                style="native",
                noclasses=True,
                prestyles="""
                                     background-color: #1C1C1C;
                                     border-radius: 5px;
                                     color: #D0D0D0;
                                     display: block;
                                     font: 11px Monaco, monospace;
                                     margin: 0;
                                     overflow: auto;
                                     padding: 15px;
                                     -webkit-border-radius: 5px;
                                     -moz-border-radius: 5px;
                                     """,
            ),
        )
        embedded = (
            embedded.replace('\\"', '\\\\"')
            .replace("'", "\\'")
            .replace("\\", "\\\\")
            .replace("background: #202020", "")
        )
        self.embedded = embedded

        snipt = super(Snipt, self).save(*args, **kwargs)

        diff = self._unidiff_output(self.original_code or "", self.code)

        if diff != "":
            log_entry = SniptLogEntry(
                user=self.last_user_saved, snipt=self, code=self.code, diff=diff
            )
            log_entry.save()

        return snipt

    def __unicode__(self):
        return self.title

    def favs(self):
        return Favorite.objects.filter(snipt=self).count()

    def get_stylized_min(self):
        if self.stylized_min is None:
            if self.lexer == "markdown":
                self.stylized_min = markdown(self.code[:1000], "default")
            else:
                self.stylized_min = highlight(
                    self.code[:1000],
                    get_lexer_by_name(self.lexer, encoding="UTF-8"),
                    HtmlFormatter(linenos="table", linenospecial=1, lineanchors="line"),
                )
        return self.stylized_min

    def get_absolute_url(self):

        if self.blog_post:
            if self.user.profile.blog_domain:
                return u"http://{}/{}/".format(
                    self.user.profile.blog_domain.split(" ")[0], self.slug
                )
            else:
                return u'https://{}.snipt.net/{}/'.format(
                    self.user.username.replace('_', '-'), self.slug)

        if self.custom_slug:
            return u"/{}/".format(self.custom_slug)

        if self.public:
            return u"/{}/{}/".format(self.user.username, self.slug)
        else:
            return u"/{}/{}/?key={}".format(self.user.username, self.slug, self.key)

    def get_full_absolute_url(self):

        if self.blog_post:
            if self.user.profile.blog_domain:
                return u"http://{}/{}/".format(
                    self.user.profile.blog_domain.split(" ")[0], self.slug
                )
            else:
                return u'https://{}.snipt.net/{}/'.format(
                    self.user.username, self.slug)

        if self.public:
            return u"/{}/{}/".format(self.user.username, self.slug)
        else:
            return u"/{}/{}/?key={}".format(self.user.username, self.slug, self.key)

    def get_download_url(self):

        try:
            lexer_obj = get_lexer_by_name(self.lexer)
        except ClassNotFound:
            lexer_obj = None

        if lexer_obj and lexer_obj.filenames:
            filename = lexer_obj.filenames[0].replace("*", self.slug)
        else:
            if self.lexer == "markdown":
                filename = u"{}.md".format(self.slug)
            else:
                filename = u"{}.txt".format(self.slug)

        return u"/download/{}/{}".format(self.key, filename)

    def get_embed_url(self):

        if settings.DEBUG:

snipts/forms.py
from django.forms import ModelForm
from snipts.models import Snipt


class SniptForm(ModelForm):
    class Meta:
        model = Snipt

snipts/templates/snipts/detail.html
{% extends "base.html" %}

{% load humanize pygmentize snipt_tags %}

{% block add-snipt %}
  {% include 'add-snipt.html' %}
{% endblock %}

{% block page-title %}/ {% if snipt.title %}{{ snipt.title }}{% else %}Untitled{% endif %} / {{ user.username }} - {{ block.super }}{% endblock %}
{% block html-class %}detail{% endblock %}
{% block body-class %}{% if request.path == '/api/' or request.path == '/blogging/' %}snipt-page{% else %}detail{% endif %}{% endblock %}

{% block js %}
        {{ block.super }}
        window.detail = true;
{% endblock %}

{% block breadcrumb %}
    <li><a href="/{{ user.username }}/">{{ user.username }}</a></li>
    <li><span class="prompt">/</span> <a href="{{ snipt.get_absolute_url }}">{{ snipt.title }}</a></li>
{% endblock %}

{% block aside-inner %}
    {% if request.path == '/api/' %}
        {% if request.user.is_authenticated %}
            <aside class="api-info api-creds">
                <div class="api-inner">
                    <h5>Your API credentials:</h5>
                    <ul>
                        <li>Username: <strong>{{ request.user.username }}</strong></li>
                        <li>User ID: <strong>{{ request.user.id }}</strong></li>
                        <li>API Key: <br /><input type="text" value="{{ request.user.api_key.key }}" /></li>
                    </ul>
                </div>
            </aside>
        {% endif %}
        <aside class="api-info immediate-help">
            <div class="api-inner">
                <h5>Need immediate help?</h5>
                <p>Ping &ldquo;nicksergeant&rdquo; in <strong>#snipt</strong> on irc.freenode.net.</p>
            </div>
        </aside>
    {% endif %}
{% endblock %}

{% block content %}
    <section class="snipts" id="snipts">
        {% with 'true' as detail %}
            {% include "snipts/snipt-list.html" %}
        {% endwith %}
        <div class="secure-view-log" id="secure-view-log">
          {% for secure_view in snipt.sniptsecureview_set.all|dictsortreversed:"created" %}
            <footer class="snipt-attrs">
              <ul class="attrs">
                <li class="author">
                  <span class="avatar" style="background-image: url('https://secure.gravatar.com/avatar/{{ secure_view.user.email|md5 }}?s=15&amp;d=https://snipt.s3.amazonaws.com/img/author-icon.png');"></span>
                  <a href="{{ secure_view.user.get_absolute_url }}">{{ secure_view.user.username }} ({{ secure_view.user.email }})</a>
                </li>
                <li class="created" title="{{ secure_view.created|date:"Y-m-d\TH:i:s" }}">{{ secure_view.created|naturaltime }}</li>
              </ul>
            </footer>
          {% endfor %}
        </div>
        <div class="snipt-log" id="history">
          {% for log_entry in snipt.sniptlogentry_set.all|dictsortreversed:"created" %}
            <section class="code autumn">
              {{ log_entry.diff|pygmentize|safe }}
            </section>
            <footer class="snipt-attrs">
              <ul class="attrs">
                <li class="author">
                  <span class="avatar" style="background-image: url('https://secure.gravatar.com/avatar/{{ log_entry.user.email|md5 }}?s=15&amp;d=https://snipt.s3.amazonaws.com/img/author-icon.png');"></span>
                  <a href="{{ log_entry.user.get_absolute_url }}">{{ log_entry.user.username }}</a>
                </li>
                <li class="created" title="{{ log_entry.created|date:"Y-m-d\TH:i:s" }}">{{ log_entry.created|naturaltime }}</li>
              </ul>
            </footer>
          {% endfor %}
        </div>
    </section>
{% endblock %}

snipts/templates/snipts/embed.html
{% if 'snipt' in request.GET %}document.addEventListener('DOMContentLoaded', function() { document.getElementById('snipt-embed-{{ snipt.key }}').innerHTML = '<div class="snipt-embed" onmouseover="document.getElementById(\'snipt-flag-{{ snipt.id }}\').style.display = \'block\'; return false;" onmouseout="document.getElementById(\'snipt-flag-{{ snipt.id }}\').style.display = \'none\'; return false;" style="position: relative;">{% for line in lines %}{{ line|safe }}\n{% endfor %}<div style="background-color: #111; color: #D0D0D0; float: right; padding: 5px 10px; -moz-border-radius-topleft: 5px; -webkit-border-top-left-radius: 5px; border-top-left-radius: 5px; -moz-border-radius-bottomright: 5px; -webkit-border-bottom-right-radius: 5px; border-bottom-right-radius: 5px; font: 11px Arial,Sans-Serif; display: none; position: absolute; bottom: 0; right: 0;" id="snipt-flag-{{ snipt.id }}">code hosted by <a href="https://snipt.net/{{ snipt.user }}/{{ snipt.slug }}{% if not snipt.public %}?key={{ snipt.key }}{% endif %}" style="color: #0084FF; text-decoration: none;">snipt.net</a></div></div>'; });
{% else %}document.open();document.writeln('<div class="snipt-embed" onmouseover="document.getElementById(\'snipt-{{ snipt.id }}\').style.display = \'block\'; return false;" onmouseout="document.getElementById(\'snipt-{{ snipt.id }}\').style.display = \'none\'; return false;" style="position: relative;">');{% for line in lines %}document.writeln('{{ line|safe }}');{% endfor %}document.writeln('<div style="background-color: #111; color: #D0D0D0; float: right; padding: 5px 10px; -moz-border-radius-topleft: 5px; -webkit-border-top-left-radius: 5px; border-top-left-radius: 5px; -moz-border-radius-bottomright: 5px; -webkit-border-bottom-right-radius: 5px; border-bottom-right-radius: 5px; font: 11px Arial,Sans-Serif; display: none; position: absolute; bottom: 0; right: 0;" id="snipt-{{ snipt.id }}">code hosted by <a href="https://snipt.net/{{ snipt.user }}/{{ snipt.slug }}{% if not snipt.public %}?key={{ snipt.key }}{% endif %}" style="color: #0084FF; text-decoration: none;">snipt.net</a></div>');document.writeln('</div>');document.close();{% endif %}

snipts/templates/snipts/list-public.html
{% extends "snipts/list.html" %}

{% block add-snipt %}
  {% include 'add-snipt.html' %}
{% endblock %}

{% block breadcrumb %}
    <li><a href="/public/">public</a></li>
    {% if tag %}
        <li><span class="prompt">/</span> <a href="/public/tag/{{ tag.slug }}/">{{ tag.name }}</a></li>
    {% endif %}
    <li class="rss">
        <a href="{{ request.path }}?rss">RSS</a>
    </li>
    {% if has_snipts %}
        <li class="compact">
            <a ng-click="$root.account.list_view = 'C'" href>Compact</a>
        </li>
        <li class="normal">
            <a ng-click="$root.account.list_view = 'N'" href>Normal</a>
        </li>
    {% endif %}
{% endblock %}

snipts/templates/snipts/list-user.html
{% extends "snipts/list.html" %}

{% block add-snipt %}
  {% include 'add-snipt.html' %}
{% endblock %}

{% block breadcrumb %}
    <li><a href="/{{ user.username }}/">{{ user.username }}</a></li>
    {% if tag %}
        <li><span class="prompt">/</span> <a href="/{{ user.username }}/tag/{{ tag.slug }}/">{{ tag.name }}</a></li>
    {% endif %}
    {% if favorites %}
        <li><span class="prompt">/</span> <a href="/{{ user.username }}/favorites/">Favorited snipts</a></li>
    {% endif %}
    <li class="rss">
        <a href="{{ request.path }}?rss">RSS</a>
    </li>
    {% if snipts %}
        <li class="compact">
            <a ng-click="$root.account.list_view = 'C'" href>Compact</a>
        </li>
        <li class="normal">
            <a ng-click="$root.account.list_view = 'N'" href>Normal</a>
        </li>
    {% endif %}
{% endblock %}

{% block aside-top %}
    {% include "profile.html" %}
    {% include "snipts/tags-user.html" %}
{% endblock %}

snipts/templates/snipts/raw.html
{% if 'nice' not in request.GET %}{{ snipt.code|safe }}{% else %}<!DOCTYPE html>
    <html lang="en">
    <head>
        <title>{{ snipt.title }}</title>
        <meta charset="utf-8" />
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/raw.css" />
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/themes.css" />
    </head>
    <body>
        <div class="autumn">
            {{ snipt.stylized|safe }}
        </div>
    </body>
</html>{% endif %}

snipts/templates/snipts/snipt-edit-js-template.html
{% load snipt_tags %}

{% get_lexers as 'lexers' %}

{% verbatim %}
    <script id="edit" type="text/html">
        <header class="fixed-save">
            <div class="inner group">
                <% if (snipt.id) { %>
                    <button class="delete btn btn-danger">Delete</button>
                <% } %>
                <button class="save-and-close btn btn-success">Save and Close</button>
                <button class="save btn btn-success">Save</button>
                <button class="cancel btn btn-secondary">Cancel</button>
            </div>
        </header>
        <div class="inner">
            <section class="snipts" id="snipts">
                <article id="snipt-<%= snipt.id %>" class="snipt editing">
                    <div class="group">
                        <div class="container">
                            <header>
                                <h2>&nbsp;</h2>
                                <h1>
                                    <input maxlength="255" type="text" id="snipt_title" placeholder="Title" value="<% if (snipt.title != 'Untitled') { %><%= snipt.title %><% } %>" />
                                </h1>
                            </header>
                            <section class="code">
                                <div class="editor"></div>
                                <textarea class="editor hidden"><% snipt.code %></textarea>
                            </section>
                            <div class="ruler top-x"></div>
                            <div class="ruler bottom-x"></div>
                        </div>
                        <aside>
                            <div class="in">
                                <% if (snipt.new_from_js) { %>
                                  {% endverbatim %}
                                  {% if request.user.profile.has_teams %}
                                    <div class="user">
                                      <label class="user">
                                          <span>User / team</span>
                                          <select name="user" id="id_user">
                                                <option value="{{ request.user.username }}">{{ request.user.username }}</option>
                                              {% for team in request.user.profile.teams %}
                                                <option value="{{ team.slug }}">{{ team.name }}</option>
                                              {% endfor %}
                                          </select>
                                      </label>
                                    </div>
                                  {% endif %}
                                  {% verbatim %}
                                <% } %>
                                <div class="type-lexer">
                                  <label class="lexer type-lexer">
                                      <span>Type</span>
                                      <select name="lexer" id="id_lexer">
                                          {% endverbatim %}
                                          {% for lexer in lexers %}
                                              <option value="{{ lexer.1.0 }}">{{ lexer.0 }}</option>
                                          {% endfor %}
                                          {% verbatim %}
                                      </select>
                                  </label>
                                </div>
                                <label class="public is-private">
                                    <input type="checkbox" <% if (snipt.public) { %>checked="checked"<% } %> name="" value="" />
                                    <span>Public</span>
                                    <div class="info private">
                                      Private snipts do not appear in the public listing, but are accessible via the direct URL.
                                    </div>
                                    <div class="info public">
                                      Public snipts are accessible by all Snipt.net users and appear in the public listing.
                                    </div>
                                </label>
                                <label class="secure">
                                    <input type="checkbox" <% if (snipt.secure) { %>checked="checked"<% } %> name="" value="" />
                                    <span>Secure</span>
                                    <div class="info">
                                      Secure snipts are available by the direct URL, but require the user to be logged in, and views are recorded with the viewer's username.
                                    </div>
                                </label>
                                <label class="blog-post is-blog-post">
                                    <input type="checkbox" <% if (snipt.blog_post) { %>checked="checked"<% } %> name="" value="" />
                                    <span>Blog post</span>
                                </label>
                                <label class="publish-date hidden">
                                    <span>Publish date</span>
                                    <input type="text" placeholder="now, 8pm, tomorrow, 12/25/07, etc." value="<%= snipt.publish_date %>" />
                                </label>
                                <label class="tags">
                                    <span>Tags</span>
                                    <textarea placeholder='tag-1, "tag 2", tag3, etc.'><%= snipt.tags_list %></textarea>
                                </label>
                                <label class="description">
                                    <span>Description</span>
                                    <textarea name="description" placeholder='optional'><% if (snipt.description && snipt.description !== 'None') { %><%= snipt.description %><% } %></textarea>
                                </label>
                            </div>
                            <div class="editor-settings">
                                <h2>Editor settings <a href="/account/" target="blank">change &raquo;</a></h2>
                                <h4>F11 or Cmd+Enter toggles fullscreen mode</h4>
                                <label class="lexer"><span>Editor<span></label>
                                <select name="editor" id="id_editor">
                                    <option value="codemirror" selected="selected">CodeMirror</option>
                                    <option value="textarea">Textarea</option>
                                </select>
                                <label class="lexer"><span>Theme<span></label>
                                <select name="theme" id="id_theme">
                                    <option value="default">Default</option>
                                    <option value="ambiance">Ambiance</option>
                                    <option value="blackboard">Blackboard</option>
                                    <option value="cobalt">Cobalt</option>
                                    <option value="eclipse">Eclipse</option>
                                    <option value="elegant">Elegant</option>
                                    <option value="erlang-dark">Erlang Dark</option>
                                    <option value="lesser-dark">Lesser Dark</option>
                                    <option value="monokai">Monokai</option>
                                    <option value="neat">Neat</option>
                                    <option value="night">Night</option>
                                    <option value="rubyblue">Ruby Blue</option>
                                    <option value="solarized dark">Solarized Dark</option>
                                    <option value="solarized light">Solarized Light</option>
                                    <option value="twilight">Twilight</option>
                                    <option value="vibrant-ink">Vibrant Ink</option>
                                    <option value="xq-dark">XQ Dark</option>
                                </select>
                            </div>
                        </aside>
                    </div>
                </article>
            </section>
        </div>
        <div class="left-y ruler"></div>
        <div class="right-y ruler"></div>
    </script>
{% endverbatim %}

snipts/templates/snipts/tags-user.html
<section class="tags">
    <div class="alt-links">
        {% if request.user == user %}
            <a href="/{{ user }}/favorites/" class="alt-link favorites {% if 'favorites' in request.path %}active{% endif %}"><span>View favorited snipts &raquo;</span></a>
        {% endif %}
        {% if user.profile.get_blog_posts %}
            <a href="/{{ user }}/blog-posts/" class="alt-link {% if 'blog-posts' in request.path %}active{% endif %}"><span>View blog posts &raquo;</span></a>
        {% endif %}
    </div>
    {% if tags %}
        <h1>{{ user.username }}'s tags</h1>
        <ul>
            {% for t in tags %}
                <li>
                    <a {% if tag.name == t.name %}class="active"{% endif %} href="/{{ user.username }}/tag/{{ t.slug }}/"><span>{{ t.name }}</span></a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</section>